<a href="https://colab.research.google.com/github/kjaid0341-creator/DATA-SCIENCE--1/blob/main/lec6.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
dct={
    "name":["Tom Hooland","Toone Stroke","Bruce Bunder","Lalala land"],
    "age":[20,30,40,50],
    "roll no":[1,2,3,4]
}
df=pd.DataFrame(dct)#convert the data into row and coloumn form
print(df)#it will not print data in proper format
# for proper format
display(df)
# for proper indexes in data
df=pd.DataFrame(dct,index=["a","b","c","d"])
display(df)

           name  age  roll no
0   Tom Hooland   20        1
1  Toone Stroke   30        2
2  Bruce Bunder   40        3
3   Lalala land   50        4

           name  age  roll no
0   Tom Hooland   20        1
1  Toone Stroke   30        2
2  Bruce Bunder   40        3
3   Lalala land   50        4

           name  age  roll no
a   Tom Hooland   20        1
b  Toone Stroke   30        2
c  Bruce Bunder   40        3
d   Lalala land   50        4

In [ ]:
import pandas as pd
df=pd.read_csv("student_data.csv")
display(df.head())#print the first five data as a default value from data
display(df.tail())#print the last five data as a default value from data
display(df.shape)#give the shape of data(rows,coloumns)
df.info()#give the information about data
df.describe()#gives the statstics of the data like std,mean,min,max
display(df.columns)#gives all columns name
display(df.index)#gives range of index

,study_hours,attendance,sleep_hours,internet_usage,assignments_completed,previous_score,exam_score,placement_status
0,7,56,8,7,10,62,100.00,Placed
1,4,69,5,3,8,56,100.00,Placed
2,11,60,7,6,10,45,100.00,Placed
3,8,99,9,8,4,55,90.17,Placed
4,5,52,8,6,8,40,78.82,Placed

,study_hours,attendance,sleep_hours,internet_usage,assignments_completed,previous_score,exam_score,placement_status
9995,2,58,9,7,8,88,69.31,Not Placed
9996,7,98,6,9,4,87,100.00,Placed
9997,10,44,8,5,10,37,95.94,Placed
9998,10,75,7,5,8,52,88.61,Placed
9999,2,70,6,11,16,52,78.96,Placed

(10000, 8)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 8 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   study_hours            10000 non-null  int64
 1   attendance             10000 non-null  int64
 2   sleep_hours            10000 non-null  int64
 3   internet_usage         10000 non-null  int64
 4   assignments_completed  10000 non-null  int64
 5   previous_score         10000 non-null  int64
 6   exam_score             10000 non-null  float64
 7   placement_status       10000 non-null  object
dtypes: float64(1), int64(6), object(1)
memory usage: 625.1+ KB

Index(['study_hours', 'attendance', 'sleep_hours', 'internet_usage',
       'assignments_completed', 'previous_score', 'exam_score',
       'placement_status'],
      dtype='object')

RangeIndex(start=0, stop=10000, step=1)

In [ ]:
#Now data manupilations
import pandas as pd
df=pd.read_csv("student_data.csv")
# to view specific coloumn datas
# df[['study_hours', 'attendance']]

# to ascess the specific row data
# df.iloc[3]

# df.iloc[3:6]#for a particular range of row data exciuding the last range

# df.loc[df['study_hours']==11]#filter all the data which are having 'study_hours values 11

# df.loc[df['study_hours']==11,['study_hours','previous_score']]#gives the 'study_hours','previous_score' datas which has 'study_hours'=11

# df.loc[df['study_hours']==11,['study_hours','previous_score']].iloc[3:6]#gives the data of a particular range
# df.iloc[4]#iloc work even if the given index in iloc is present in data or not it take the index value as serial wise
df.loc[4]#loc can also work as iloc if the same index value are present in the data or not
# if index value are a,b,c,d,e,f,g,h and iloc[2]it will print the b index data loc[2]it will not print the data it only works if loc['a'] is given

study_hours                   5
attendance                   52
sleep_hours                   8
internet_usage                6
assignments_completed         8
previous_score               40
exam_score                78.82
placement_status         Placed
Name: 4, dtype: object

In [ ]:
import pandas as pd
df=pd.read_csv("student_data.csv")
# df.loc[df['assignments_completed']==8,['assignments_completed']].iloc[1:2]


# display(df.loc[df["assignments_completed"]>3])
# display(df[df["assignments_completed"]>3])
#both do same work

# To rename a coloumn
# df=df.rename(columns={"assignments_completed":"ass_completed"})#return the new data frame or whole data with row and coloumn
# display(df)

# to add a column in the data frame
# df["age"]=20
# display(df)

# to remove row a coloumn
df = df.drop('sleep_hours', axis=1)#to remove a particular coloumn axis=1
# display(df)
# for Drop multiple columns:
df = df.drop(columns=['internet_usage', 'previous_score'],axis=1)
# display(df)
# Drop rows by index label:
df = df.drop([0, 1])
# display(df)

# for removing Null values
df=df.dropna()

# sort index
df2=df.sort_index(ascending=False)#return the decending value of the sorted index
display(df2)
#
df1=df.sort_values(by="assignments_completed",ascending=False)
display(df1)

#check the missing values
df3=df.isnull()

# check for non missing values
# df3=df.notisnull()

# replace missing values
# df4=df.fillna()

# find unique values
df["attendance"].unique()

,study_hours,attendance,assignments_completed,exam_score,placement_status
9999,2,70,16,78.96,Placed
9998,10,75,8,88.61,Placed
9997,10,44,10,95.94,Placed
9996,7,98,4,100.00,Placed
9995,2,58,8,69.31,Not Placed
...,...,...,...,...,...
6,10,40,9,98.12,Placed
5,7,40,0,72.33,Placed
4,5,52,8,78.82,Placed
3,8,99,4,90.17,Placed
2,11,60,10,100.00,Placed

,study_hours,attendance,assignments_completed,exam_score,placement_status
6641,7,56,20,100.00,Placed
6642,10,69,20,100.00,Placed
1026,1,57,20,83.45,Placed
1042,5,98,20,100.00,Placed
1043,11,99,20,100.00,Placed
...,...,...,...,...,...
6873,6,58,0,58.06,Not Placed
6869,8,49,0,79.17,Placed
58,2,89,0,69.17,Not Placed
5,7,40,0,72.33,Placed
6665,6,96,0,89.00,Placed

array([ 60,  99,  52,  40,  86,  72,  77,  64,  65,  98,  67,  76,  80,
        69,  96,  88,  87,  47,  95,  51,  44,  63,  45,  71,  81,  42,
        58,  82,  68,  89,  41,  48,  56,  85,  75, 100,  59,  43,  54,
        55,  50,  94,  93,  73,  61,  90,  66,  49,  97,  70,  84,  74,
        92,  46,  91,  83,  79,  78,  57,  62,  53])